from mzt.jit.assembler import (
    encode_add_imm,
    encode_add_reg,
    encode_adrp,
    encode_b,
    encode_b_cond,
    encode_bl,
    encode_blr,
    encode_br,
    encode_cbnz,
    encode_cbz,
    encode_cmp_imm,
    encode_cmp_reg,
    encode_ldp_offset,
    encode_ldp_post,
    encode_ldr_offset,
    encode_ldr_post_imm,
    encode_ldr_pre_imm,
    encode_mov_from_sp,
    encode_mov_reg,
    encode_movk,
    encode_movn,
    encode_movz,
    encode_ret,
    encode_str_offset,
    encode_str_post_imm,
    encode_str_pre_imm,
    encode_stp_offset,
    encode_stp_pre,
    encode_sub_imm,
    encode_sub_reg,
    COND_EQ,
    COND_LT,
    COND_NE,
)


REFERENCE_ENCODINGS: list[tuple[str, int]] = [
    ("ret",                              encode_ret()),
    ("ret x0",                           encode_ret(0)),
    ("ret x29",                          encode_ret(29)),
    ("br x9",                            encode_br(9)),
    ("br x19",                           encode_br(19)),

    ("blr x9",                           encode_blr(9)),
    ("blr x16",                          encode_blr(16)),

    ("bl #0",                            encode_bl(0)),
    ("bl #4",                            encode_bl(4)),
    ("bl #-4",                           encode_bl(-4)),
    ("bl #400",                          encode_bl(400)),
    ("b #0",                             encode_b(0)),
    ("b #4",                             encode_b(4)),
    ("b #-4",                            encode_b(-4)),

    ("b.eq #0",                          encode_b_cond(COND_EQ, 0)),
    ("b.eq #4",                          encode_b_cond(COND_EQ, 4)),
    ("b.ne #0",                          encode_b_cond(COND_NE, 0)),
    ("b.lt #0",                          encode_b_cond(COND_LT, 0)),
    ("b.lt #4",                          encode_b_cond(COND_LT, 4)),
    ("b.lt #-4",                         encode_b_cond(COND_LT, -4)),

    ("cbz x0, #0",                       encode_cbz(0, 0)),
    ("cbz x0, #4",                       encode_cbz(0, 4)),
    ("cbz x19, #0",                      encode_cbz(19, 0)),
    ("cbnz x0, #0",                      encode_cbnz(0, 0)),

    ("movz x0, #42",                     encode_movz(0, 42, 0)),
    ("movz x21, #0",                     encode_movz(21, 0, 0)),
    ("movz x0, #16, lsl #16",            encode_movz(0, 16, 16)),
    ("movz x0, #16, lsl #32",            encode_movz(0, 16, 32)),
    ("movz x0, #16, lsl #48",            encode_movz(0, 16, 48)),
    ("movk x0, #42",                     encode_movk(0, 42, 0)),
    ("movn x0, #0",                      encode_movn(0, 0, 0)),
    ("movn x0, #1",                      encode_movn(0, 1, 0)),

    ("add x0, x0, #0",                   encode_add_imm(0, 0, 0)),
    ("add x0, x0, #1",                   encode_add_imm(0, 0, 1)),
    ("add x0, x0, #8",                   encode_add_imm(0, 0, 8)),
    ("mov x29, sp",                      encode_mov_from_sp(29)),
    ("sub x0, x0, #8",                   encode_sub_imm(0, 0, 8)),
    ("sub x19, x19, #8",                 encode_sub_imm(19, 19, 8)),

    ("add x0, x0, x0",                   encode_add_reg(0, 0, 0)),
    ("add x0, x0, x1",                   encode_add_reg(0, 0, 1)),
    ("sub x0, x0, x1",                   encode_sub_reg(0, 0, 1)),

    ("adrp x0, #0",                      encode_adrp(0, 0)),
    ("adrp x1, #0",                      encode_adrp(1, 0)),

    ("str x0, [x19, #-8]!",              encode_str_pre_imm(0, 19, -8)),
    ("str x0, [sp, #-8]!",               encode_str_pre_imm(0, 31, -8)),
    ("str x0, [x19], #8",                encode_str_post_imm(0, 19, 8)),
    ("str x0, [x0]",                     encode_str_offset(0, 0, 0)),
    ("str x0, [x19]",                    encode_str_offset(0, 19, 0)),
    ("str x0, [x19, #8]",                encode_str_offset(0, 19, 8)),
    ("str x0, [x19, #16]",               encode_str_offset(0, 19, 16)),
    ("str xzr, [x19, #-8]!",             encode_str_pre_imm(31, 19, -8)),

    ("ldr x0, [x19, #-8]!",              encode_ldr_pre_imm(0, 19, -8)),
    ("ldr x0, [x19], #8",                encode_ldr_post_imm(0, 19, 8)),
    ("ldr x0, [x19]",                    encode_ldr_offset(0, 19, 0)),
    ("ldr x0, [x19, #8]",                encode_ldr_offset(0, 19, 8)),
    ("ldr x0, [x19, #16]",               encode_ldr_offset(0, 19, 16)),

    ("stp x29, x30, [sp, #-16]!",        encode_stp_pre(29, 30, 31, -16)),
    ("ldp x29, x30, [sp], #16",          encode_ldp_post(29, 30, 31, 16)),
    ("stp x0, x0, [x19]",                encode_stp_offset(0, 0, 19, 0)),
    ("stp x0, x1, [x19]",                encode_stp_offset(0, 1, 19, 0)),
    ("ldp x0, x1, [x19]",                encode_ldp_offset(0, 1, 19, 0)),
    ("ldp x0, x1, [x19, #16]",           encode_ldp_offset(0, 1, 19, 16)),

    ("cmp x0, #0",                       encode_cmp_imm(0, 0)),
    ("cmp x19, #0",                      encode_cmp_imm(19, 0)),
    ("cmp x1, x0",                       encode_cmp_reg(1, 0)),
    ("cmp x19, x0",                      encode_cmp_reg(19, 0)),

    ("mov x0, x0",                       encode_mov_reg(0, 0)),
    ("mov x0, x19",                      encode_mov_reg(0, 19)),
    ("mov x19, x0",                      encode_mov_reg(19, 0)),
]
